language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g https://github.com/Financial-Times/origami-build-tools/tarball/master#cf5cf4d2910fa1019760d22024b71aabfd1b324b
  - origami-build-tools install
script:
  - origami-build-tools test